"""App generator wizard."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict


@dataclass(frozen=True)
class GeneratedAppPlan:
    app_name: str
    app_type: str
    files: Dict[str, str] = field(default_factory=dict)
    commands: tuple[str, ...] = ()
    dry_run: bool = True

    def to_dict(self) -> dict:
        return {
            "app_name": self.app_name,
            "app_type": self.app_type,
            "files": dict(self.files),
            "commands": list(self.commands),
            "dry_run": self.dry_run,
        }


def generate_app_plan(app_name: str, app_type: str = "web") -> GeneratedAppPlan:
    if not app_name.strip():
        raise ValueError("app_name required")
    if app_type not in {"web", "api", "creative", "agent", "saas"}:
        raise ValueError(f"unsupported app_type: {app_type}")
    slug = app_name.strip().lower().replace(" ", "-")
    files = {
        f"apps/{slug}/README.md": f"# {app_name}\\n\\nGenerated by ZAI App Studio.\\n",
        f"apps/{slug}/app.json": f'{{"name":"{app_name}","type":"{app_type}"}}\\n',
    }
    commands = (f"mkdir -p apps/{slug}", f"write generated files for {slug}")
    return GeneratedAppPlan(app_name=app_name, app_type=app_type, files=files, commands=commands)
